services:
  postgres:
    image: postgres:17-alpine

    environment:
      POSTGRES_DB: akari
      POSTGRES_USER: ${DB_USERNAME:-akari}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-akari}

    ports:
      - "5432:5432"

    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

    restart: unless-stopped

  rclone:
    image: rclone/rclone:1.75.1

    command: rcd --rc-no-auth --rc-addr 0.0.0.0:5572 --log-file /var/log/rclone/rclone.log

    ports:
      - "5572:5572"

    volumes:
      - ./data/rclone-logs:/var/log/rclone

    restart: unless-stopped
